package com.company;

public class Main {

    public static void main(String[] args) {
        System.out.println(Reverse("AAAACCCGGT"));
    }

    public static String Reverse(String t){
        char[] tArr = t.toCharArray();
        int low = 0;
        int high = tArr.length;
        while(low < high){
            char temp = tArr[low];
            tArr[low] = tArr[high];
            tArr[high] = tArr[temp];
            low ++;
            high--;
        }
        return t;
    }

    public static String RNA(String t) {
        //String used = "TCTGGTTTAGCCCGCACGACGACACCGTATGCCGACGCGGCGTTGCTCCTGACAGTTTATTCTTCAACCCGGTTGGTTCAGGAATTGATTGAGTACGAGAGCGTGGTGTTATAGCCTCTGTAGTCACCAGTCGAGATCCTGTGGTTTTTTGTAGAATCCCCAAAGCGTGGCCGTAGAAGGCACCCGTGCGTTCGGCCTGCGACCGGGTACTAGGCCTGACAGGACTACCTGTCAACAATGGCCCGACTCGCGAACACTAGGTGCTGCAAAGCGTCTATTGGATGGATAGCCCCACTACAGGTTGGGCCCTAGTGGAGGAGTACGATATTGCACGTTATGATAGCGACACTACGTATCAACTTCCCGTAAAGTGTCATCACACGCGTACGGTTAGACTCTCCTGATGTGATTTGAGTAGACTGCTTGCGGACGAGTGCGGGGTAAATGGCTTCTATTATGTTTCGCCTTACACGATGGCTTAGGATTAGACCGTATTCGATACCTGATAGCTCACTATCCCTATTTAAATCATTCAGCGGGTAAATATCGCGACATTATCGCAAGGCCCGTTTCCCCTCCGCCGGCCTAAAAGCCGTGCGGCATGTGGCGGTGTAGACTTCATTAACCACAAAGCCCAAACTCGAACACTGATAGGGGGACCTGGGAGACAGAGGCCCACCAAGTCATATCCAAGACGAACTTGTTTCGACCGGTTCGCACAACCTTGGAATCTGTGCCATTTTGTGAAATTTTTGACGTCATCAGGAGGCGTTCGCTTAGCGCCCCGCTACCCACCCCGCTAGGCTGCTGGGTCCTGGGCTAAGGAGGTAGTAAGCACTCCATTATAGTCAGTATACCAAAACTGACGATGATATCGCCGTGGACGACGAAAATGGGGGTGGCCAGTCAGTTGGTTGTTTGCGCTGCCTGGTGACCAATCAGGATCGATCAGGAGACTTT\n");
        String newt = t.replace('T', 'U');
        return newt;
    }
}
